# reference of
# https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-Ubuntu-14.04
---
- name: setup apt key of hhvm
  apt_key: url=http://dl.hhvm.com/conf/hhvm.gpg.key

- name: setup hhvm repo
  copy: src=hhvm.list 
        dest=/etc/apt/sources.list.d/hhvm.list

- name: install the hhvm
  apt: name=hhvm
       state=latest
       update_cache=yes
